apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpbin
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # Target 80% CPU utilization before scaling up.
        averageUtilization: 80