apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  labels:
    app: httpbin
# --- Best Practice: Security ---
# Disable automatic mounting of the service account token, as this application
# does not need to communicate with the Kubernetes API server.
automountServiceAccountToken: false
